title: Hi Im Thewave
email: null@gmail.com
description: "Hi Im Thewave"
baseurl: "/"
url: "https://thewavewsp.github.io"
twitter_username: best magisk module
github_username:  best magisk
author: The Wave


plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
